// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AuditHistory(arg1:string):Promise<Array<backend.Audit>>;

export function BatchReceipt(arg1:string):Promise<backend.Receipt>;

export function BatchStatus(arg1:string):Promise<backend.Compartment>;

export function DeadLetters():Promise<number>;

export function DispatchBatch(arg1:string,arg2:Array<number>):Promise<string>;

export function DispatchChaos(arg1:string,arg2:Array<number>):Promise<string>;

export function Fleet():Promise<Array<backend.Worker>>;

export function GetConfig():Promise<backend.Config>;

export function LocalReceipts():Promise<Array<backend.Receipt>>;

export function RedriveDLQ(arg1:number):Promise<number>;

export function SaveConfig(arg1:backend.Config):Promise<void>;
