// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuditHistory(arg1) {
  return window['go']['main']['App']['AuditHistory'](arg1);
}

export function BatchReceipt(arg1) {
  return window['go']['main']['App']['BatchReceipt'](arg1);
}

export function BatchStatus(arg1) {
  return window['go']['main']['App']['BatchStatus'](arg1);
}

export function DeadLetters() {
  return window['go']['main']['App']['DeadLetters']();
}

export function DispatchBatch(arg1, arg2) {
  return window['go']['main']['App']['DispatchBatch'](arg1, arg2);
}

export function DispatchChaos(arg1, arg2) {
  return window['go']['main']['App']['DispatchChaos'](arg1, arg2);
}

export function Fleet() {
  return window['go']['main']['App']['Fleet']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function LocalReceipts() {
  return window['go']['main']['App']['LocalReceipts']();
}

export function RedriveDLQ(arg1) {
  return window['go']['main']['App']['RedriveDLQ'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
